### ISSUE TITLE
What should be public facing on din-foundation?

### ISSUE THREAD

**Issue by gtl-hig** [DIN-Foundation/wallet#3]
Internal discussions, internal decisions and resource management can be kept here. What should go to a public facing din-foundation project?

**Comment by vongohren** [comment]
@gtl-hig since it is free private repos I dont feel that there is a difference between din and this.
I just want to be able to showcase more movement in DIN so people see that there are efforst towards this better digital identity.

We can rather package it in a public facing versus private repo in my mind.

That way we can invite people as we go into the different teams and all is good.

I dont even mind having something public that is not ready, it still showcase movement and its easier for people to get engaged into the conversation

**Comment by vongohren** [comment]
Any one up to doing this all in DIN with private repos?
Any movement is good movement for DIN. That can be private movement as well.
But as you go to https://github.com/Diwala fex, you see there is no public facing members and only a couple of open repos. All happen in the private. But that doesnt restrict us in any ways.

We can use teams and private repos in adjusting access.

So i still vote for moving everything over to https://github.com/DIN-Foundation.

**Comment by vongohren** [comment]
@gtl-hig any thoughts? I have even notified you on the team in din-foundation. Alot can be kept private there

**Comment by vongohren** [comment]
Just reverbarating what is in the last bump email: "This Im leaning even more towards just using teams inside DIN i have tried to showcase cool features that that can offer and it can also provide a sense of being apart of something bigger. It also looks cool to have it on your github profile, an authentic team :D"

**Comment by gtl-hig** [comment]
Let us continue here, and play with NTNU team on DIN to get a feel how things can be done. 

There are issues to be resolved: 
* teams and organisations are a bit tightly integrated, such that all organisation members see everything, but, they cannot mess up things they do not have write/admin permission to
* only organisation owners can add/remove team members. E.g. NTNU team does not have Abylay in, and I cannot add him into a team without being an organisation owner, which is not a good access management 
* the students should be able to control who and how participates in their project, and that is to some extent possible through teams, but, organisation owners can see and do anything anyway, so the sense of ownership is reduced

I am in favour of open development and open source license and I do not see any option to do things differently, in the context of digital identity work. However, at the same time we are discussing here Bachelor project and we need to honour student rights - it is student decision what they want to do with it at the end of the project.   So - I suggest we continue here, and, when ready, migrate to DIN team.

**Comment by vongohren** [comment]
Thanks for your argumenst @gtl-hig, i just have to provide my feedback on it. Which again leaves me at the state of mind that we should move to DIN-foundation.

### "teams and organisations are a bit tightly integrated......."
The visibility of things is completely open to change, on all levels
<img width="1370" alt="Screenshot 2020-11-19 at 14 52 14" src="https://user-images.githubusercontent.com/1012055/99675066-0d724700-2a77-11eb-9740-84f0b8eb32b5.png">
I dont understand your argument about messing up, as this is acctually a postive thing?
And you are argumenting from a private perspective is better, where I truely believe in transparency, rather than privacy. In most of the cases I would cheer for, transparency have triumphed, and privacy has just added hinders to them. People are people, and they do behave, if not them there are mechanisms to make sure that if an error happens, things can be controlled or turned back.

### "only organisation owners can add/remove team members......"
Wrong, I had just not made you controller. I can even make you a organization owner, you are integrated into the future of DIN as much as I am almoast. Through our talks and initiatives. This is again just a non profit repo.

### "the students should be able to control who and how participates in their project,......"
Not sure what you are afraid of here? That there comes some organization owners into DIN that would create a negative effect on the project? I would not worry about that at all. If there were owners coming in, I believe they would provide puerly positive effect than negative. This again is backed by the transparnecy mindset.

### " However, at the same time we are discussing here Bachelor project and we need to honour student rights - it is student decision what they want to do with it at the end of the project."
I respect this, and lets ask then. I have asked that is part of my argument "The feeling of beeing part of something bigger. "


# Some of my own arguments for
### The feeling of beeing part of something bigger. 
I believe that can be quite valueble. I got a question from another student group, if this would acctually be tallied for something useful? That they were able to contribute to value? They triggered on the reply of yes. Which comes back to

### Transparency and feeling of movement
If we work on the boundaries of DIN and create movement and some transparent discussions it can bring in more interessting view points in Norway. So what I want is to showcase that there are people interested in this, there are people wanting to do tech on this, and through that, engage even more people to provide knowledge.
Yes I can always showcase the link to this repo, but again, we both want DIN to succeed because we believe that for SSI to happen, there needs to be a bigger umbrella speaking the word of SSI, for a better push.
So in this stage, all movement is good movement. In movement I mean that something is happening.

### Lets try to take the steps we can to showcase DIN creates value.
It supports on the thing above. The privace and ownership is restored within the organization without any troubles in my mind. But we need to work on this together. You even have din in the name of this organization :P Doesnt make sense to not move it in the other place

**Comment by abylays** [comment]
I don't see any negative impact for students if we move it to DIN. As I know many bachelor projects previously collaborated with private companies and have done tasks given by them. Here DIN is a non-profit and all student repositories and works will be transparent, so that they can showcase their work in future. Being part of DIN can widen opportunities for students. If all issues related to access/control can be solved, I am for moving the project to DIN from the start.

**Comment by gtl-hig** [comment]
@Arxcis this is primarily your decision. If you would like to keep things "less" official and continue to work, here, we stay here. If you are OK migrating to DIN-Foundation under NTNU teams, we can migrate. 

@vongohren can you make me an owner of DIN-Foundation?  One can only add members to teams if they are part of the organisation, and one can only add members to organisation if one is an owner.

**Comment by Arxcis** [comment]
I am FOR doing the project on `github.com/din-foundation`, if that is what you are asking? I appreciate that the students oppinion is taken into consideration :pray:  I know a lot would choose to keep everything as private as possible. I love the freedom to have privacy, whenever I want. But in this case, I think it is more important to be open about the work that is being done. I already have some experience of working out in the open on Github, so this is something I am very comfortable with :+1: 

Sorry for the late answer, but I was waiting to make a decision about this, until the entire group was assembled.

**Comment by marni** [comment]
OK guys, done. I've migrated the repo to `DIN-Foundation`, and I'm going to "remove" the other `din-ssi` placeholder from github now. Closing this issue.

**Comment by marni** [comment]
Funny enough, I need to be an admin to be able to close issues, so, this one remains open for now - to be closed by @vongohren  ;)

**Comment by vongohren** [comment]
Did you still have issues with: https://github.com/DIN-Foundation/wallet/issues/3#issuecomment-732749829?
